export {default as Navbar} from './Navbar'
export {default as Categories} from './Categories'
export {default as Products} from './Products'
export {default as Footer} from './Footer'
export {default as Cart} from './Cart'
